[전체편집]2019-pyconkr/day2/라이트닝 토크/How to Have Fun with PY - 유희열.txt
pythonkr/pyconkr-script pull request #71
Opened 2020-03-21 17:23 UTC by constmoon

# 영상 자막 기여하기

파이콘 한국은 많은 기여자 분들과 함께 만들어집니다. 더 많은 분들이 파이콘 한국을 접하는 데 도움을 주셔서 감사합니다.

* PR 제목은 `[전체편집] 파일경로` 또는 `[일부수정] 파일경로`를 입력해주세요.
  * 예시1: `[전체편집]2019-pyconkr/day2/라이트닝 토크/what is my PyCon - 배권한.txt`
  * 예시2: `[일부수정]2019-pyconkr/day2/라이트닝 토크/what is my PyCon - 배권한.txt`

## 작업 내용

* 이전에 생성한 이슈 번호: #70 

## 제출 전 다시한번

- [x] PR(Pull Request) 전에 이슈를 먼저 생성해주세요.
- [x] 중복된 PR 이 없는지 확인해주세요.
- [x] 적절한 파일 제목을 입력해주세요. 빠른 반영에 큰 도움이 됩니다.
- [x] 파일 이름이 변경되지 않았는지 확인해주세요. 변경되었다면 원래의 파일명으로 수정한 뒤 제출 부탁드립니다.
- [x] [CoC](https://pycon.kr/2020/about/coc/)에 부적절한 내용은 없는지 확인해주세요. CoC에 위반한 내용이 있다면 `Reject` 될 수 있습니다.
- [x] 스크립트의 일부분을 수정 기여하셨다면, 스크립트 내에 검수한 부분을 표시해주세요. 

   * 검수한 스크립트 내용 앞에 줄을 추가해 `(여기부터 검수 시작)` 을 적어주시고 검수한 내용 마지막 줄에 `(여기까지 검수완료)` 를 추가해 적어주세요.
	* 모든 내용이 검수 완료된 스크립트는 마지막 줄에 `(검수완료)` 라고 적어주세요.
- [x] Maintainer가 수정할 수 있도록 `Allow edits from maintainers` 항목을 체크해주세요. 

## 이슈번호 확인 방법

* 이슈 번호는 아래의 위치에서 확인하실 수 있습니다.

<img src="./check-issue-number.png" alt="이슈번호 확인방법" style="zoom:60%;" />

2020-03-21 17:33 UTC, constmoon commented
## 질문
발표자가 대화를 인용할 경우 자막에는 어떻게 표시해야하는지 궁금합니다.

  - 예를 들어, 기존 스크립트에선 아래와 같이 나와있습니다.
    ```
    그런데 저는 코딩 못한다고 했더니, 이거 사실 입코딩 하는 사람들 걸러내는 정직도 테스트라고 하는 거예요.
    ```
    그런데 이 스크립트가 발표자의 대사와 맞지 않아 아래와 같이 수정했습니다.
    ```
    그래서 "저 코딩 못해요"라고 했어요.
    그랬더니 "이거 사실 입코딩 하는 사람들 걸러내는 거라, 정직도 테스트에요" 라고 하시는 거에요.
    ```
    이럴 경우 큰따옴표(`" "`)를 사용하는 게 글쓰기에서 일반적이긴 하나, 자막에도 같은 규칙이 적용되는지 궁금합니다.
    ```
    > 그랬더니 "이거 사실 입코딩 하는 사람들 걸러내는 거라,
    > 정직도 테스트에요" 라고 하시는 거에요.
    ```
    문장이 길어질 경우 따옴표가 분리되는 상황이 일어나는데, 문제 없는 표기법인가요?

  - 간접 인용의 경우, 인용 구절이 길어지거나 여러 문장을 인용할 경우 처리하기가 어려울 것 같다고 생각이 듭니다. 그러나 문자통역 결과물에는 전부 간접 인용으로 표기되어있어, 표준이 어떻게 되는지 알고 싶어요.

2020-03-23 10:31 UTC, ohahohah commented
문자통역사분이 적으신 거 보다 지우님 수정본이 발화자의 내용과 더 가까운 거 같아서 좋고요!

큰 따옴표가 없다고 해도 가독성이 확 떨어지지는 않는 거 같아요. 지우님 방법과 큰 따옴표 없이 적는 방법 둘 다 괜찮아보여요. 저는 둘 중 하나로 정해지면 상관없습니다~

2020-03-23 10:34 UTC, syohnet requested changes
작업 감사합니다! 엄청 생생하게 발표가 느껴지네요ㅋㅋㅋㅋㅋ

2020-03-23 10:34 UTC, ohahohah commented on 2019-pyconkr/day2/라이트닝 토크/How to Have Fun with PY - 유희열.txt
> +저는 일단 재밌는 사람이구요. 이거를 있다가 임포트 할 거라서
오타있어요~ 있다가 -> 이따가

2020-03-24 02:23 UTC, jylee1164 approved these changes
따옴표 쓰셔서 대화문을 표시해 주신 게 가독성이나 대화 흐름 파악에 좋은 것 같아요~!

2020-04-11 12:58 UTC, constmoon commented
오탈자 수정하여 푸쉬했습니다.

2020-04-13 01:00 UTC, syohnet approved these changes

2020-04-14 08:14 UTC, merged

2020-06-25 00:37 UTC, ohahohah commented
@all-contributors please add constmoon for content